services:
  # frontend container
  todo-app:
    build:
      context: ./app
    depends_on:
      - todo-database
    environment:
      # NODE_ENV: production
      PORT: 3000
      MONGODB_URL: mongodb://db_container:27017
      DB_NAME: daily-tasks
      NAME: daily-tasks
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync

  # Mongobd container
  todo-database:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - todo-database:/data/db

volumes:
  todo-database: {}
